CREATE USER IF NOT EXISTS 'ga-app'@'%' IDENTIFIED BY 'ga-5ecret-%';
CREATE USER IF NOT EXISTS 'ga-app'@'localhost' IDENTIFIED BY 'ga-5ecret-%';

GRANT ALL PRIVILEGES ON *.* TO 'ga-app'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'ga-app'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;